const path = require('path')
console.log(path.sep)
console.log({ __dirname })
let relative = path.join('node', 'miniNode', 'microtxt.js')
console.log({ relative })
let basename = path.basename(relative)
console.log({ basename })
let absoulte = path.resolve(__dirname, relative)
console.log({absoulte})